language: go

go:
  - 1.7.1

addons:
  apt:
    packages:
      - python-pygments

env:
  global:
    - COMMIT_AUTHOR_EMAIL: oriol.mauri@devcows.com
    - ENCRYPTION_LABEL: 7adb43d426f2

before_install:
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOPATH/bin

install:
  - wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.20.7/hugo_0.20.7_Linux-ARM.tar.gz
  - tar xvzf /tmp/hugo.tar.gz

before_script:
  - mkdir themes
  - git clone --depth 1 https://github.com/ryanfox1985/hugo-orbit-theme.git themes/hugo-orbit-theme/

script:
  - hugo

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master

notifications:
  slack: devcows:bJqjHDL6xXdgga0I5r0yzM7z
