# Page settings

baseurl = "https://maguri.github.io/cv/"
languageCode = "en-us"
title = "Oriol Mauri CV"
theme = "hugo-orbit-theme"
googleAnalytics = ""

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Oriol Mauri Guiu"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles_oriol.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Oriol Mauri Guiu"
        tagline = "Software Engineer"
        avatar = "hugo-avatar.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = ""
        icon = ""
        url = "http://www.onthisday.com/date/1995/february/13"
        title = "February 13, 1995"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: oriol.mauri@devcows.com"
        title = "oriol.mauri@devcows.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+34671097625"
        title = "+(34) 671 09 76 25"

        # [[params.contact.list]]
        # class = "website"
        # icon = "fa-globe"
        # url = "//portfoliosite.com"
        # title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://es.linkedin.com/in/oriol-mauri-193a648b"
        title = "Oriol Mauri Guiu"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/maguri"
        title = "@maguri"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/oriolmauriguiu"
        title = "@oriolmauriguiu"

    # Education section
    [params.education]
        enable = true
        title = "Education"
        [[params.education.list]]
        degree = "High School Diploma"
        college = "Lestonnac L'Ensenyança"
        dates = "2007 - 2013"

        [[params.education.list]]
        degree = "Software Engineer"
        college = "University Rovira i Virgili"
        dates = "2013 - 2017"

        [[params.education.list]]
        degree = "English B2 Certificate"
        college = "ESOL English Cambridge"
        dates = " July 2016"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "B2 (CEFR)"

        [[params.languages.list]]
        language = "Spanish"
        level = "Native"

        [[params.languages.list]]
        language = "Catalan"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "New technologies"

        [[params.interests.list]]
        interest = "Surf"

        [[params.interests.list]]
        interest = "Aikido"

        [[params.interests.list]]
        interest = "Human towers"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am an enterprising, creative, different from the others and eager to fulfill my dreams and illusions. Born in a mediterranean city, Tarragona, I love the nature and the peace of the sea at the same time I adore the new technologies and frameworks that make this world easy for every body. My dream is work some day for a big company who give me the opportunity to take part of their projects to improve this world and change the people arround it. I love be friendly and get out with my friends at the weekends, and as a practitioner of Aikido I respect a lot the people and I work very well with small groups of people. I have work developing and deploing web apps with Django and Ruby on Rails following the MVC Pattern."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "College Internship"
        dates = "2015 - Present"
        company = "DevCows, Spain, Catalonia Tarragona"
        details = "**Web Developer** in [DevCows](http://www.devcows.com/): Web app developer of the back and front end of a [Django](https://www.djangoproject.com/) web app for a private company. I have learn how to use [Vagrant](https://www.vagrantup.com/) and [Docker](https://www.docker.com/). Working in a small group with continuous integration using [GitLab](https://gitlab.com) and [Heroku](https://www.heroku.com) for the test environment and deploy. Getting new knowledges about [Yeoman](yeoman.io), [Coveralls](https://coveralls.io/), [Semaphore](https://semaphoreci.com), [Trello](https://trello.com/) and more things. My bosses and partners were [Adrian Moreno](https://www.linkedin.com/in/adrianmorenomartinez) and [Guillermo Ibarra](https://www.linkedin.com/in/guillermoguerreroibarra), software engineers, great web developers and teachers. "

        [[params.jobs.list]]
        position = "Student"
        dates = "2013 - 2017"
        company = "Rovira i Virgili University, Spain, Catalonia, Tarragona"
        details = "**Student** in [URV](http://urv.cat/) - [ETSE](http://etse.urv.cat/) - [DEIM](http://deim.urv.cat/) as a Software engineer. We are involved in all aspects of software creation, from writing code to debugging programs to overseeing the launch of new software. They often start out writing code but eventually advance to senior positions, working as software architects or project managers. In a software engineer career, it’s essential to keep up with the latest advancements, because technology is constantly evolving. Having strong interpersonal and management skills is also crucial since software engineers often collaborate with marketing, manufacturing, and design professionals in creating new software."

        [[params.jobs.list]]
        position = "UI/IO Developer"
        dates = "2014 - 2015"
        company = "Club Natació Tarraco, Tarragona"
        details = "**Software Engineer** in [Club Natació Tarraco](www.cntarraco.cat/): We deploy an input and output system to contoll the access of the customers in the swimming club."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**Projects**: I have participated in a lot of projects in my degree as student like develop an Operative System for Nintendo DS, Develop a game like The 'Candy Crash' also for Nintendo DS, or programme the game of the tron with Python for the linux shell, programme 'sockets' in C, Design, make and manage a local network or deploy an own web app with Java, Ruby on Rails or Django."

        [[params.projects.list]]
        title = "Shining – Intelligent Street Lighting"
        url = "https://bitbucket.org/engineer_coders/distributed-systems"
        tagline = "Private project that implements a distributed system that simulate a smart city light system and that use [PyActive](https://github.com/cloudspaces/pyactive) and [Redis](http://redis.io/)."

        [[params.projects.list]]
        title = "Simple CV with Hugo"
        url = "https://github.com/maguri/cv"
        tagline = "Simple Curriculum Vitae with a Theme for Hugo. Deployed on GitHub Pages, Tested and monitorized by [Travis CI](https://travis-ci.org/maguri/cv)"

        [[params.projects.list]]
        title = "Dashboard Tap"
        url = "https://github.com/maguri/dashboard-tap"
        tagline = "(in progress). This is a project to customize new tap on a browser of any developer or user"

        [[params.projects.list]]
        title = "Go Share your Giphy"
        url = "#"
        tagline = "(in progress). This is a web app developed with Go lang. This is a connection between Giphy API and Facebook API to share automatically giphies on your facebook page"

        [[params.projects.list]]
        title = "The internet of Feed"
        url = "#"
        tagline = "(in progress). This is a web service connected with microservices who give to the system all the necessary information to know the percentages of the nutrients of a person and know everything about what he should do and he should not eat or do."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Java OOP"
        level = "90%"

        [[params.skills.list]]
        skill = "C, ARM, Embadded & RTS"
        level = "75%"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "75%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "55%"

        [[params.skills.list]]
        skill = "Android"
        level = "40%"

        [[params.skills.list]]
        skill = "React.js & Angular"
        level = "10%"

        [[params.skills.list]]
        skill = "Scala, Elixir & Golang"
        level = "10%"


    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Oriol Mauri Guiu"
